on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: deploy
        uses: demurgos/ga-deploy-git@v1
        with:
          accessToken: ${{ secrets.PUSH_TOKEN }}
          commitEmail: "accounts+github@jitesoft.com"
          commitUser: "Jitesoft Bot"
          destBranch: "gh-pages"
          srcDir: "./"
